/* Cubby — the teaching registry.
   ------------------------------------------------------------------------------------------------
   One row per capability. Every teaching surface renders from here, and the marketing FAQ section
   generates from here, because content written twice is content that drifts — and drifted teaching
   copy is worse than none: it tells a parent something the app no longer does.

   DEPTH IS A PROPERTY OF THE ROW, not a separate tier list.
     every row      -> `one`, the one-line answer. Feeds the info dot, the answer search, the FAQ.
     + what/get     -> earns a guide chapter.
     + earn         -> may compete for the day's allowance. NO `earn` MEANS IT CAN NEVER PUSH,
                       which is a structural guarantee rather than a matter of discipline.

   `who` narrows who is ever offered a row. It may only narrow, never widen: a row can be stricter
   than the shell but must never claim a surface the shell would not open for that person. Mood is
   owner-only and must stay owner-only in the ANSWER SEARCH too — gating the dot while leaving the
   row findable would leak the existence of a private record to a caregiver.

   NO_TEACH is not a leftovers bin. It is the other half of the coverage gate: every entry point in
   the app is in one of these two objects, each exclusion carrying its reason in writing. The count
   was wrong twice before it was right (a shell-only grep misses the modules; four entry points are
   `window.X = function` assignments no `function open*` pattern catches), which is the whole
   argument for the gate existing.

   Generated once from the reconciled 148-entry classification, then maintained by hand.
*/
(function () {
  'use strict';

  var TEACH = {
    /* ---- Everyday logging (23) ---- */
    openFeed: { label: 'Feed', fn: 'openFeed()', domain: 'log', depth: 'chapter',
      one: 'Breast, bottle, water or solids, with a live timer for nursing.',
      who: { stage: ['baby','child'] } },
    openSleep: { label: 'Sleep', fn: 'openSleep()', domain: 'log', depth: 'chapter',
      one: 'Start a nap with one tap. The timer shows on every phone in your circle.',
      who: { stage: ['baby','child'] },
      earn: { on: 'first-log' } },
    openDiaper: { label: 'Diaper', fn: 'openDiaper()', domain: 'log', depth: 'chapter',
      one: 'Wet, dirty, both, or a dry check. The thing a doctor almost always asks about.',
      who: { stage: ['baby','child'] } },
    openPump: { label: 'Pump', fn: 'openPump()', domain: 'log', depth: 'chapter',
      one: 'How much you expressed, which side, and when.',
      who: { stage: ['baby','child'] } },
    openActivity: { label: 'Add to the day', fn: 'openActivity()', domain: 'log', depth: 'chapter',
      one: 'Tummy time, a bath, a walk, or a line about the day. Add a photo if you took one.',
      who: { stage: ['baby','child'] } },
    openGrowth: { label: 'Measurement', fn: 'openGrowth()', domain: 'log', depth: 'chapter',
      one: 'Weight and height whenever you have them. One of the two is fine.',
      who: { stage: ['baby','child'] },
      earn: { on: 'growth-2-points' } },
    openMilestone: { label: 'Milestone', fn: 'openMilestone()', domain: 'log', depth: 'chapter',
      one: 'The firsts, from a library of ideas or in your own words.',
      who: { stage: ['baby','child'] },
      earn: { on: 'month-1' } },
    openCustomMilestone: { label: 'New moment', fn: 'openCustomMilestone()', domain: 'log', depth: 'one',
      one: 'A first that is not on anybody\'s list but yours.',
      who: { stage: ['baby','child'] } },
    openQuickLog: { label: 'Quick log', fn: 'openQuickLog()', domain: 'log', depth: 'chapter',
      one: 'The one-tap row on your home screen. You choose which four sit there.',
      who: { stage: ['baby','child'] },
      earn: { on: 'logs-10' } },
    openFirstLog: { label: 'Your first log', fn: 'openFirstLog()', domain: 'log', depth: 'one',
      one: 'The very first entry, opened straight from the empty home screen.',
      who: { stage: ['baby','child'] } },
    openMoreLogs: { label: 'More logs', fn: 'openMoreLogs()', domain: 'log', depth: 'one',
      one: 'The early-days logs, whenever you need them: feed, diaper, pump.',
      who: { stage: ['baby','child'] },
      earn: { on: 'logs-5' } },
    openAddEntry: { label: 'Add to Cubby', fn: 'openAddEntry()', domain: 'log', depth: 'one',
      one: 'Every log in one list, when the quick row does not have what you want.',
      who: { stage: ['baby','child'] },
      earn: { on: 'logs-25' } },
    openPastFeed: { label: 'Past feed', fn: 'openPastFeed()', domain: 'log', depth: 'one',
      one: 'A feed that already happened. Late is fine, nothing has to be logged live.',
      who: { stage: ['baby','child'] },
      earn: { on: 'logs-10' } },
    openPastSleep: { label: 'Finished nap', fn: 'openPastSleep()', domain: 'log', depth: 'one',
      one: 'A nap that ended before you got to your phone.',
      who: { stage: ['baby','child'] } },
    openSleepOngoing: { label: 'Already napping', fn: 'openSleepOngoing()', domain: 'log', depth: 'one',
      one: 'They drifted off a while ago. Set when it actually started.',
      who: { stage: ['baby','child'] },
      earn: { on: 'sleep-logged-3' } },
    openEdit: { label: 'Fix an entry', fn: 'openEdit()', domain: 'log', depth: 'chapter',
      one: 'Wrong day, wrong time, a nap\'s wake time. Mistakes are meant to be fixable.',
      who: { stage: ['baby','child'] },
      earn: { on: 'first-log' } },
    openTrash: { label: 'Recently deleted', fn: 'openTrash()', domain: 'log', depth: 'one',
      one: 'Deleted entries wait here before they go for good.',
      who: { stage: ['baby','child'] },
      earn: { on: 'first-delete' } },
    openDayLog: { label: 'The whole day', fn: 'openDayLog()', domain: 'log', depth: 'one',
      one: 'Everything logged on one day, in order.',
      who: { stage: ['baby','child'] },
      earn: { on: 'logs-25' } },
    openDayRecap: { label: 'Day recap', fn: 'openDayRecap()', domain: 'log', depth: 'one',
      one: 'How the day went, gathered into one read.',
      who: { stage: ['baby','child'] },
      earn: { on: '7-days-logged' } },
    openRoutinesEdit: { label: 'Rituals', fn: 'openRoutinesEdit()', domain: 'log', depth: 'chapter',
      one: 'The rhythm you are building. A gentle \'four of seven\', never a streak.',
      who: { stage: ['baby','child'] },
      earn: { on: '7-days-logged' } },
    openRoutineItem: { label: 'A ritual', fn: 'openRoutineItem()', domain: 'log', depth: 'one',
      one: 'One ritual, and how this week has gone for it.',
      who: { stage: ['baby','child'] } },
    openActivityPhoto: { label: 'Photo on an activity', fn: 'openActivityPhoto()', domain: 'log', depth: 'one',
      one: 'The photo lands in your album, tagged with the day it belongs to.',
      who: { stage: ['baby','child'] },
      earn: { on: 'first-photo' } },
    openVoiceLog: { label: 'Say it', fn: 'openVoiceLog()', domain: 'log', depth: 'chapter',
      one: 'Speak a feed, a nap or a nappy and Cubby writes it down. You confirm before it saves.',
      who: { stage: ['baby','child'] },
      earn: { on: 'logs-25' } },

    /* ---- Health and guidance (19) ---- */
    openTemp: { label: 'Temperature', fn: 'openTemp()', domain: 'health', depth: 'chapter',
      one: 'A reading, with plain guidance beside it. Cubby never diagnoses.',
      who: { stage: ['baby','child'] },
      earn: { on: 'month-2' } },
    openSymptom: { label: 'Symptom', fn: 'openSymptom()', domain: 'health', depth: 'chapter',
      one: 'How they are, in your words or from a list.',
      who: { stage: ['baby','child'] },
      earn: { on: 'temp-logged' } },
    openStartIllness: { label: 'Feeling poorly?', fn: 'openStartIllness()', domain: 'health', depth: 'chapter',
      one: 'Start tracking an illness, so the timeline is ready for the call.',
      who: { stage: ['baby','child'] },
      earn: { on: 'temp-logged' } },
    openCondition: { label: 'A condition', fn: 'openCondition()', domain: 'health', depth: 'one',
      one: 'Something ongoing, kept where the rest of the health record is.',
      who: { stage: ['baby','child'] } },
    openManageConditions: { label: 'Health trackers', fn: 'openManageConditions()', domain: 'health', depth: 'one',
      one: 'Turn on only the trackers that apply to you.',
      who: { stage: ['baby','child'] } },
    openAddMed: { label: 'Add a medicine', fn: 'openAddMed()', domain: 'health', depth: 'chapter',
      one: 'What you gave, how much, and when. Two people cannot double a written-down dose.',
      who: { stage: ['baby','child'] },
      earn: { on: 'illness-started' } },
    openMedSheet: { label: 'A medicine', fn: 'openMedSheet()', domain: 'health', depth: 'chapter',
      one: 'The dose, the schedule, and when the last one was given, by whom.',
      who: { stage: ['baby','child'] },
      earn: { on: 'med-added' } },
    openMedManage: { label: 'Manage medicines', fn: 'openMedManage()', domain: 'health', depth: 'one',
      one: 'Everything currently prescribed, in one place.',
      who: { stage: ['baby','child'] } },
    openDoseCalendar: { label: 'Doses in your calendar', fn: 'openDoseCalendar()', domain: 'health', depth: 'chapter',
      one: 'Set times go into your own calendar, so the alarm comes from something you already trust.',
      who: { stage: ['baby','child'] },
      earn: { on: 'med-added' } },
    openVaccine: { label: 'A vaccine', fn: 'openVaccine()', domain: 'health', depth: 'chapter',
      one: 'One vaccine, when it is due, and whether it has been given.',
      who: { stage: ['baby','child'] },
      earn: { on: 'birthday-set' } },
    openVaccineCountry: { label: 'Vaccine schedule', fn: 'openVaccineCountry()', domain: 'health', depth: 'chapter',
      one: 'The schedule for where you are, filled in the day you gave a birthday.',
      who: { stage: ['baby','child'] },
      earn: { on: 'birthday-set' } },
    openAddVaccine: { label: 'Add a vaccine', fn: 'openAddVaccine()', domain: 'health', depth: 'one',
      one: 'Something your schedule does not include.',
      who: { stage: ['baby','child'] } },
    openVisitSummary: { label: 'Visit summary', fn: 'openVisitSummary()', domain: 'health', depth: 'chapter',
      one: 'The things a doctor usually asks, gathered into one page you can read out.',
      who: { stage: ['baby','child'] },
      earn: { on: 'fever' } },
    openDoctorReport: { label: 'Last 14 days', fn: 'openDoctorReport()', domain: 'health', depth: 'chapter',
      one: 'A fortnight of the record, ready to hand over.',
      who: { stage: ['baby','child'] },
      earn: { on: 'appt-added' } },
    openVisit: { label: 'Log a visit', fn: 'openVisit()', domain: 'health', depth: 'one',
      one: 'What was said, while you still remember it.',
      who: { stage: ['baby','child'] },
      earn: { on: 'appt-added' } },
    openDoctor: { label: 'Your doctor', fn: 'openDoctor()', domain: 'health', depth: 'one',
      one: 'Who you see, and how to reach them.',
      who: { stage: ['baby','child'] },
      earn: { on: 'illness-started' } },
    openDoctorEdit: { label: 'Edit doctor', fn: 'openDoctorEdit()', domain: 'health', depth: 'one',
      one: 'Keep the details current.',
      who: { stage: ['baby','child'] } },
    openFoodPrefs: { label: 'Food and allergies', fn: 'openFoodPrefs()', domain: 'health', depth: 'one',
      one: 'What they eat, what they react to, what to avoid.',
      who: { stage: ['baby','child'] },
      earn: { on: 'month-5' } },
    openReadingRoom: { label: 'Reading room', fn: 'openReadingRoom()', domain: 'health', depth: 'chapter',
      one: 'Short reads that match the stage you are in. Written and sourced, never generated.',
      who: { stage: ['baby','child'] },
      earn: { on: 'week-1' } },

    /* ---- Pregnancy (29) ---- */
    openStartPregnancy: { label: 'Start a pregnancy', fn: 'openStartPregnancy()', domain: 'preg', depth: 'chapter',
      one: 'Tell Cubby you are expecting, and everything reshapes around it.',
      who: { stage: ['pregnancy'] } },
    openExpectingSetup: { label: 'Expecting setup', fn: 'openExpectingSetup()', domain: 'preg', depth: 'one',
      one: 'Due date, and how you would like the weeks counted.',
      who: { stage: ['pregnancy'] } },
    openEditPregnancy: { label: 'Due date and schedule', fn: 'openEditPregnancy()', domain: 'preg', depth: 'one',
      one: 'Change the date, change the schedule. Nothing is locked in.',
      who: { stage: ['pregnancy'] } },
    openWeekDetail: { label: 'This week', fn: 'openWeekDetail()', domain: 'preg', depth: 'chapter',
      one: 'What is happening this week, without a countdown.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'pregnancy-started' } },
    openKickCounter: { label: 'Kick counter', fn: 'openKickCounter()', domain: 'preg', depth: 'chapter',
      one: 'Count the movements in one sitting. You learn what usual looks like for your baby.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-28' } },
    openContractions: { label: 'Contraction timer', fn: 'openContractions()', domain: 'preg', depth: 'chapter',
      one: 'How long, and how far apart, so you are not guessing on the phone.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-36' } },
    openLogSymptom: { label: 'Log a symptom', fn: 'openLogSymptom()', domain: 'preg', depth: 'chapter',
      one: 'How you are feeling, so appointments are not done from memory.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-6' } },
    openLogWeight: { label: 'Your weight', fn: 'openLogWeight()', domain: 'preg', depth: 'one',
      one: 'Yours, not the baby\'s. Kept private to you.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-10' } },
    openLogBP: { label: 'Blood pressure', fn: 'openLogBP()', domain: 'preg', depth: 'one',
      one: 'A reading, with the numbers your midwife will want.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-20' } },
    openBPWatch: { label: 'Blood pressure watch', fn: 'openBPWatch()', domain: 'preg', depth: 'one',
      one: 'When someone has asked you to keep an eye on it.',
      who: { stage: ['pregnancy'] } },
    openGlucoseLog: { label: 'Blood glucose', fn: 'openGlucoseLog()', domain: 'preg', depth: 'one',
      one: 'A reading, in the units you were given.',
      who: { stage: ['pregnancy'] } },
    openGlucoseTracker: { label: 'Gestational diabetes', fn: 'openGlucoseTracker()', domain: 'preg', depth: 'chapter',
      one: 'The readings, the targets you were given, and the pattern between them.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'condition-added' } },
    openUrineLog: { label: 'Urine protein', fn: 'openUrineLog()', domain: 'preg', depth: 'one',
      one: 'What the dipstick said, kept with the rest.',
      who: { stage: ['pregnancy'] } },
    openNausea: { label: 'Nausea and hydration', fn: 'openNausea()', domain: 'preg', depth: 'one',
      one: 'How rough it has been, and whether you are keeping fluids down.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-6' } },
    openSupplements: { label: 'Supplements and meds', fn: 'openSupplements()', domain: 'preg', depth: 'one',
      one: 'What you are taking while expecting.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-4' } },
    openAntenatalFacts: { label: 'Your antenatal record', fn: 'openAntenatalFacts()', domain: 'preg', depth: 'chapter',
      one: 'Blood group, screening, scans. The flowsheet a midwife recognises.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'appt-added' } },
    openAddAppt: { label: 'Add appointment', fn: 'openAddAppt()', domain: 'preg', depth: 'chapter',
      one: 'Scans and checks, with the reminder in your own calendar.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'pregnancy-started' } },
    openApptEdit: { label: 'An appointment', fn: 'openApptEdit()', domain: 'preg', depth: 'one',
      one: 'Move it, change it, or note what happened.',
      who: { stage: ['pregnancy'] } },
    openVisitPrep: { label: 'Prep for your visit', fn: 'openVisitPrep()', domain: 'preg', depth: 'chapter',
      one: 'What to ask, gathered before you go in.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'appt-added' } },
    openPregDoctorReport: { label: 'Pregnancy doctor report', fn: 'openPregDoctorReport()', domain: 'preg', depth: 'chapter',
      one: 'One printable page of everything you have kept.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-20' } },
    openDangerSigns: { label: 'Urgent warning signs', fn: 'openDangerSigns()', domain: 'preg', depth: 'chapter',
      one: 'When to call, in plain words. Not a diagnosis, a threshold.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-12' } },
    openAddCareTeam: { label: 'Care team', fn: 'openAddCareTeam()', domain: 'preg', depth: 'one',
      one: 'Midwife, obstetrician, whoever you actually call.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-8' } },
    openBag: { label: 'Hospital bag', fn: 'openBag()', domain: 'preg', depth: 'chapter',
      one: 'A list you can tick, built for the day you will not be thinking clearly.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-36' } },
    openBirthPlan: { label: 'Birth plan', fn: 'openBirthPlan()', domain: 'preg', depth: 'chapter',
      one: 'What you would prefer, written down while it is calm.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'week-34' } },
    openBirthDetails: { label: 'Birth details', fn: 'openBirthDetails()', domain: 'preg', depth: 'one',
      one: 'What happened, when, and how much they weighed.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'birth' } },
    openWelcomeBaby: { label: 'Welcome to the world', fn: 'openWelcomeBaby()', domain: 'preg', depth: 'chapter',
      one: 'The arrival screen. Pregnancy becomes a baby, and the app follows.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'birth' } },
    openPregRecord: { label: 'Your pregnancy record', fn: 'openPregRecord()', domain: 'preg', depth: 'chapter',
      one: 'The whole pregnancy, kept read-only after the birth. Nothing is overwritten.',
      who: { stage: ['pregnancy'] },
      earn: { on: 'birth' } },
    openGentleMode: { label: 'Gentle mode', fn: 'openGentleMode()', domain: 'preg', depth: 'chapter',
      one: 'Turn down everything cheerful, without turning the app off.',
      who: { stage: ['pregnancy'] } },
    openPregnancyVisibility: { label: 'Your private pregnancy', fn: 'openPregnancyVisibility()', domain: 'preg', depth: 'chapter',
      one: 'Who sees the pregnancy at all, and what they see of it.',
      who: { stage: ['pregnancy'] , role: 'owner' },
      earn: { on: 'pregnancy-started' } },

    /* ---- Trying to conceive (6) ---- */
    openPlanningSetup: { label: 'We\'re trying', fn: 'openPlanningSetup()', domain: 'trying', depth: 'chapter',
      one: 'Tell Cubby where you are. No forecasts, and no fertile-window promises.',
      who: { stage: ['planning'] } },
    openPeriodUpdate: { label: 'Period started', fn: 'openPeriodUpdate()', domain: 'trying', depth: 'chapter',
      one: 'The one thing worth recording. Everything else is drawn from it.',
      who: { stage: ['planning'] },
      earn: { on: 'trying-started' } },
    openObservation: { label: 'Today I noticed', fn: 'openObservation()', domain: 'trying', depth: 'chapter',
      one: 'What you noticed, in your own words. Nothing is scored.',
      who: { stage: ['planning'] },
      earn: { on: 'trying-started' } },
    openObsList: { label: 'Things you noticed', fn: 'openObsList()', domain: 'trying', depth: 'one',
      one: 'The diary, read back.',
      who: { stage: ['planning'] },
      earn: { on: 'obs-3' } },
    openPositiveTest: { label: 'A positive test', fn: 'openPositiveTest()', domain: 'trying', depth: 'chapter',
      one: 'When it happens, this is the door from trying into expecting.',
      who: { stage: ['planning'] },
      earn: { on: 'positive-test' } },
    openTtcDoctorReport: { label: 'Doctor report', fn: 'openTtcDoctorReport()', domain: 'trying', depth: 'chapter',
      one: 'Cycles and observations on one page, for the appointment you booked.',
      who: { stage: ['planning'] },
      earn: { on: 'trying-12mo' } },

    /* ---- Circle, sharing and privacy (12) ---- */
    openAddSomeone: { label: 'Add someone special', fn: 'openAddSomeone()', domain: 'circle', depth: 'chapter',
      one: 'Invite a partner, a grandparent, a nanny. What they log appears on your phone straight away.',
      who: { stage: null },
      earn: { on: 'logs-10' } },
    openGuardians: { label: 'Guardians', fn: 'openGuardians()', domain: 'circle', depth: 'chapter',
      one: 'Who is in the circle, and what each of them can do.',
      who: { stage: null },
      earn: { on: 'second-caregiver' } },
    openNoteCompose: { label: 'Leave a note', fn: 'openNoteCompose()', domain: 'circle', depth: 'chapter',
      one: 'A word for whoever has baby next. Everyone, or just one person.',
      who: { stage: null },
      earn: { on: 'second-caregiver' } },
    openNoteView: { label: 'A note', fn: 'openNoteView()', domain: 'circle', depth: 'one',
      one: 'The card always says who it went to.',
      who: { stage: null } },
    openMoodNote: { label: 'How are you, in yourself?', fn: 'openMoodNote()', domain: 'circle', depth: 'chapter',
      one: 'Never shared with your circle. Not now, not later, not by accident.',
      who: { stage: null, role: 'owner' },
      earn: { on: 'postpartum-2w' } },
    openMaternalPrivacy: { label: 'Your private health', fn: 'openMaternalPrivacy()', domain: 'circle', depth: 'chapter',
      one: 'The line around what stays yours, drawn where you can see it.',
      who: { stage: null , role: 'owner' },
      earn: { on: 'pregnancy-started' } },
    openConsentReview: { label: 'Consent', fn: 'openConsentReview()', domain: 'circle', depth: 'one',
      one: 'What you have agreed to, and how to change it.',
      who: { stage: null } },
    openBabySheet: { label: 'Switch baby', fn: 'openBabySheet()', domain: 'circle', depth: 'one',
      one: 'Twins, or a second child. One tap between them.',
      who: { stage: null },
      earn: { on: 'second-baby-added' } },
    openFamily: { label: 'Your circle', fn: 'openFamily()', domain: 'circle', depth: 'chapter',
      one: 'Who is in it, what each of them can do, and how to add someone. The differentiator, and the least-explained screen in the app.',
      who: { stage: null },
      earn: { on: 'first-log' } },
    openBearPicker: { label: 'Your bear', fn: 'openBearPicker()', domain: 'circle', depth: 'one',
      one: 'Mama Bear, Nana Bear, or a name you choose. It is how your entries are signed.',
      who: { stage: null },
      earn: { on: 'joined-circle' } },
    showAccessLost: { label: 'If you leave a circle', fn: 'showAccessLost()', domain: 'circle', depth: 'chapter',
      one: 'Your access goes and what you logged stays with the family. Nothing disappears from the story.',
      who: { stage: null } },
    showInviteMismatch: { label: 'When an invite does not match', fn: 'showInviteMismatch()', domain: 'circle', depth: 'one',
      one: 'The invite was sent to a different address than the one you signed in with. Fixable, not a dead end.',
      who: { stage: null } },

    /* ---- Memories and keepsakes (17) ---- */
    openAddMoment: { label: 'Add a moment', fn: 'openAddMoment()', domain: 'memories', depth: 'chapter',
      one: 'A memory worth keeping, with the day attached.',
      who: { stage: null },
      earn: { on: 'first-photo' } },
    openAddMomentAt: { label: 'Add a moment then', fn: 'openAddMomentAt()', domain: 'memories', depth: 'one',
      one: 'Something you remembered later. Put it on the day it happened.',
      who: { stage: null } },
    openMomentDetail: { label: 'A moment', fn: 'openMomentDetail()', domain: 'memories', depth: 'one',
      one: 'One memory, in full.',
      who: { stage: null } },
    openCreateMoment: { label: 'Make a moment', fn: 'openCreateMoment()', domain: 'memories', depth: 'one',
      one: 'Start from a prompt when you cannot think of one.',
      who: { stage: null } },
    openPregMoment: { label: 'A pregnancy moment', fn: 'openPregMoment()', domain: 'memories', depth: 'one',
      one: 'The ones from before they arrived.',
      who: { stage: null } },
    openJourneyRename: { label: 'Name this journey', fn: 'openJourneyRename()', domain: 'memories', depth: 'one',
      one: 'Call it what you call it.',
      who: { stage: null },
      earn: { on: 'moments-5' } },
    openMemoryCard: { label: 'Memory card', fn: 'openMemoryCard()', domain: 'memories', depth: 'chapter',
      one: 'A month, a photo and a line, made into something you would actually print.',
      who: { stage: null },
      earn: { on: '3-photos' } },
    openBirthPoster: { label: 'Birth poster', fn: 'openBirthPoster()', domain: 'memories', depth: 'chapter',
      one: 'The details of the day, set as something to put on a wall.',
      who: { stage: null },
      earn: { on: 'birth' } },
    openThenNow: { label: 'Then vs Now', fn: 'openThenNow()', domain: 'memories', depth: 'chapter',
      one: 'Two photos, months apart. The one that always lands.',
      who: { stage: null },
      earn: { on: 'photos-10' } },
    openKeptMemories: { label: 'Kept memories', fn: 'openKeptMemories()', domain: 'memories', depth: 'one',
      one: 'What you chose to keep, gathered in one place.',
      who: { stage: null } },
    openRelCapture: { label: 'A photo with someone', fn: 'openRelCapture()', domain: 'memories', depth: 'chapter',
      one: 'The first time they meet, and every time after.',
      who: { stage: null },
      earn: { on: 'second-caregiver' } },
    openRelView: { label: 'With someone', fn: 'openRelView()', domain: 'memories', depth: 'one',
      one: 'Every photo with one person, over time.',
      who: { stage: null } },
    openPhotoPrep: { label: 'Make it just right', fn: 'openPhotoPrep()', domain: 'memories', depth: 'one',
      one: 'Crop it, straighten it, warm it up. Nothing leaves your phone to do it.',
      who: { stage: null },
      earn: { on: 'first-photo' } },
    openAvatarPicker: { label: 'Profile picture', fn: 'openAvatarPicker()', domain: 'memories', depth: 'one',
      one: 'A photo or a bear. Change it whenever.',
      who: { stage: null },
      earn: { on: 'first-photo' } },
    openPetSetup: { label: 'Your pet', fn: 'openPetSetup()', domain: 'memories', depth: 'one',
      one: 'They are family too, and they show up in the story.',
      who: { stage: null } },
    openGuessGame: { label: 'Family games', fn: 'openGuessGame()', domain: 'memories', depth: 'chapter',
      one: 'Boy or girl guesses from your circle. A guess is never treated as a fact.',
      who: { stage: null },
      earn: { on: 'week-20' } },
    openPrintable: { label: 'Printable', fn: 'openPrintable()', domain: 'memories', depth: 'one',
      one: 'A version made for paper, not for a screen.',
      who: { stage: null } },

    /* ---- Setup, account and data (16) ---- */
    openAddBaby: { label: 'Add a baby', fn: 'openAddBaby()', domain: 'account', depth: 'chapter',
      one: 'A first, a second, or twins. Each gets their own everything.',
      who: { stage: null } },
    openBabyProfile: { label: 'Baby\'s profile', fn: 'openBabyProfile()', domain: 'account', depth: 'one',
      one: 'Name, birthday, and the details the rest of the app reads from.',
      who: { stage: null } },
    openStageSheet: { label: 'Change stage', fn: 'openStageSheet()', domain: 'account', depth: 'chapter',
      one: 'Trying, expecting, baby, child. You can move, and nothing is lost.',
      who: { stage: null },
      earn: { on: '18-months' } },
    openSettings: { label: 'Settings', fn: 'openSettings()', domain: 'account', depth: 'one',
      one: 'Everything about how Cubby behaves, in one list.',
      who: { stage: null } },
    openQuickSettings: { label: 'Quick log button', fn: 'openQuickSettings()', domain: 'account', depth: 'one',
      one: 'Choose the four logs on your home screen. Yours, not your household\'s.',
      who: { stage: null },
      earn: { on: 'logs-10' } },
    openAppearance: { label: 'Appearance', fn: 'openAppearance()', domain: 'account', depth: 'chapter',
      one: 'System, light or night, and it is yours alone. Your partner keeps theirs.',
      who: { stage: null },
      earn: { on: 'month-1' } },
    openReminders: { label: 'Reminders', fn: 'openReminders()', domain: 'account', depth: 'chapter',
      one: 'Due medicine only. Cubby will not nag you about logging.',
      who: { stage: null },
      earn: { on: 'med-added' } },
    openDataSheet: { label: 'Your data', fn: 'openDataSheet()', domain: 'account', depth: 'chapter',
      one: 'Where it lives, who can reach it, and how to take it with you.',
      who: { stage: null },
      earn: { on: 'month-2' } },
    openDeleteRequest: { label: 'Delete data', fn: 'openDeleteRequest()', domain: 'account', depth: 'one',
      one: 'Remove what you no longer want kept.',
      who: { stage: null } },
    openDeleteAccount: { label: 'Delete my account', fn: 'openDeleteAccount()', domain: 'account', depth: 'chapter',
      one: 'Always yours to make. The shared log stays with the circle; your name comes off it.',
      who: { stage: null } },
    openPro: { label: 'Cubby Pro', fn: 'openPro()', domain: 'account', depth: 'chapter',
      one: 'What Pro adds. Registration only until October 2026, and the copy has to say so.',
      who: { stage: null } },
    openProPortal: { label: 'Manage Pro', fn: 'openProPortal()', domain: 'account', depth: 'one',
      one: 'Your subscription, when there is one to manage.',
      who: { stage: null } },
    showSignIn: { label: 'Signing in', fn: 'showSignIn()', domain: 'account', depth: 'chapter',
      one: 'Google, Apple, or a link by email. No password to forget at 3am.',
      who: { stage: null } },
    openForm: { label: 'Sign in by email', fn: 'openForm()', domain: 'account', depth: 'one',
      one: 'A one-time link, sent to you. Nothing to remember.',
      who: { stage: null } },
    openFirstRun: { label: 'Setting up', fn: 'openFirstRun()', domain: 'account', depth: 'chapter',
      one: 'Stage, details, who you are, and who else should see it. Four steps, then you are in.',
      who: { stage: null } },
    openFeedback: { label: 'Send feedback', fn: 'openFeedback()', domain: 'account', depth: 'one',
      one: 'Tell us what is broken or missing. It reaches a person.',
      who: { stage: null },
      earn: { on: 'month-1' } },
  };

  var NO_TEACH = {
    /* Plumbing, not capability */
    openDateTimePicker: 'The shared date and time picker. One component, reused everywhere, by design.',
    openTimePicker: 'Time half of the same component.',
    openWhenPicker: 'The \'when did this happen\' control inside log sheets.',
    showStatus: 'Inline status text during sign-in.',
    showSent: 'Confirms the magic link went out.',
    openSheet: 'The sheet primitive itself. 131 call sites because it is the frame, not a feature.',
    showLoader: 'A loading spinner. It has no content of its own to explain.',
    openPickerOverlay: 'The searchable-dropdown primitive.',
    openDateModal: 'The shared date and time picker.',
    openArticle: 'Renders a read. The reading room is the capability; this is its renderer.',
    openReadCarousel: 'Renders the swipeable reads. Same reason.',
    showCountryList: 'Opens a picker\'s list. Helper inside a form field.',
    showDeletedGoodbye: 'Terminal confirmation screen after deletion. Nothing left to teach.',
    openNote: 'Dead alias: function openNote(){ openActivity(); } with zero callers. Delete it.',

    /* Dormant behind a flag */
    openDenChores: 'FEATURES.den = false.',
    openDenExpenses: 'FEATURES.den = false.',
    openDenMeals: 'FEATURES.den = false.',
    openDenShopping: 'FEATURES.den = false.',
    openDenStaff: 'FEATURES.den = false.',
    openDenWeights: 'FEATURES.den = false.',

    /* Already a teaching cue */
    showReady: 'Setup-complete screen. Part of first-run, not a thing to explain.',
    openFeverNudge: 'Already the earned nudge for the visit summary. Governed by the ledger.',
    openKeepsakeNudge: 'Already the earned nudge for memory cards.',
    openInstall: 'Already a prompt. Competes for the token like any other.',
    showBirthArrival: 'Arrival prompt. Fires on the birth transition.',
    openOnboardInvite: 'The last screen of first-run. Part of the flow, not a thing to explain.',
  };

  window.CubbyTeachData = { rows: TEACH, noTeach: NO_TEACH };
})();
