#!/usr/bin/env python3
"""Build the 2732x2732 iOS launch splash from the Cubby bear.

WHY THIS EXISTS
`npx cap add ios` ships Capacitor's own splash (a blue X on white) in Splash.imageset, and builds 1-5
carried it: every launch flashed Capacitor branding before the cream app appeared. The splash should be
the bear on Cubby cream (#F7F2E8), matching `ios.backgroundColor` and the app's own background so launch
reads as one continuous surface.

Our only bear source is icons/logo-512.png: the bear ON a cream rounded-rect gradient, with alpha
corners. A splash is not an icon — we want the bear alone on flat cream, not a pasted-on tile (the
tile's gradient edge would draw a visible square seam against #F7F2E8). So:
  1. Fit the tile's background gradient exactly as tools/gen_app_icon.py does (quadratic surface per
     channel from the opaque border band, after eroding the anti-aliased rim).
  2. Segment the bear as "everything NOT reachable from the corners through background-like pixels"
     (flood fill). Thresholding alone would lose the muzzle and blush, which are cream-coloured but
     enclosed by the brown face; flood fill keeps every enclosed region.
  3. Feather the mask edge slightly (the fringe blends toward the old cream, which is near-identical
     to the new cream, so the feather is invisible rather than a halo).
  4. Lanczos-upscale the cropped bear so its long side is ~20% of the canvas — well inside the centre
     region that survives aspect-fill cropping on every device — and composite at the optical centre
     (46% height), flattened to RGB.

`ios/` is gitignored and regenerated by `npx cap add ios`, so the generated splash is NOT durable —
re-run this after any regen (same rule as gen_app_icon.py). All three imageset scales get the same
2732 universal image, which is what Capacitor's stock Contents.json expects.

Usage: python3 tools/gen_splash.py
"""
import os
import sys
from collections import deque

import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PREFERRED = os.path.join(ROOT, 'icons', 'logo-1024.png')   # if a real 1024 ever lands, it wins
FALLBACK = os.path.join(ROOT, 'icons', 'logo-512.png')
OUT_DIR = os.path.join(ROOT, 'ios', 'App', 'App', 'Assets.xcassets', 'Splash.imageset')
OUT_NAMES = ['splash-2732x2732.png', 'splash-2732x2732-1.png', 'splash-2732x2732-2.png']
CANVAS = 2732
CREAM = (0xF7, 0xF2, 0xE8)
BEAR_FRAC = 0.20      # bear long side as a fraction of the canvas
CENTRE_Y = 0.46       # optical centre, slightly above geometric
RESID_THRESH = 14     # max per-channel diff from the fitted gradient that still counts as background

src_path = PREFERRED if os.path.exists(PREFERRED) else FALLBACK
if not os.path.exists(src_path):
    sys.exit('No source icon at %s' % src_path)

img = Image.open(src_path).convert('RGBA')
size = img.size[0]
a = np.asarray(img).astype(np.float64)
alpha = a[:, :, 3]

# Background gradient fit — same recipe as gen_app_icon.py (see there for the erosion rationale).
solid = np.asarray(
    Image.fromarray(alpha.astype(np.uint8)).filter(ImageFilter.MinFilter(9))
) == 255
band = int(size * 0.06)
yy, xx = np.mgrid[0:size, 0:size]
border = (xx < band) | (xx >= size - band) | (yy < band) | (yy >= size - band)
fit_mask = solid & border
if fit_mask.sum() < 500:
    sys.exit('Not enough opaque border pixels to fit the background gradient (got %d)' % fit_mask.sum())

def design(x, y):
    x = x / size
    y = y / size
    return np.column_stack([x, y, x * x, y * y, x * y, np.ones(len(x))])

A = design(xx[fit_mask].astype(np.float64), yy[fit_mask].astype(np.float64))
full = design(xx.ravel().astype(np.float64), yy.ravel().astype(np.float64))
bg = np.zeros((size, size, 3), dtype=np.float64)
for ch in range(3):
    coef, *_ = np.linalg.lstsq(A, a[:, :, ch][fit_mask], rcond=None)
    bg[:, :, ch] = (full @ coef).reshape(size, size)

# Background-like: matches the gradient, or is transparent (the rounded corners).
resid = np.abs(a[:, :, :3] - bg).max(axis=2)
bgish = (resid < RESID_THRESH) | (alpha < 128)

# Flood fill from the corners across background-like pixels. What the flood never reaches is the bear,
# including its enclosed cream muzzle and blush.
reached = np.zeros((size, size), dtype=bool)
q = deque()
for sy, sx in [(0, 0), (0, size - 1), (size - 1, 0), (size - 1, size - 1)]:
    if bgish[sy, sx]:
        reached[sy, sx] = True
        q.append((sy, sx))
if not q:
    sys.exit('No background-like corner to seed the flood fill from')
while q:
    y, x = q.popleft()
    if y > 0 and bgish[y - 1, x] and not reached[y - 1, x]:
        reached[y - 1, x] = True; q.append((y - 1, x))
    if y < size - 1 and bgish[y + 1, x] and not reached[y + 1, x]:
        reached[y + 1, x] = True; q.append((y + 1, x))
    if x > 0 and bgish[y, x - 1] and not reached[y, x - 1]:
        reached[y, x - 1] = True; q.append((y, x - 1))
    if x < size - 1 and bgish[y, x + 1] and not reached[y, x + 1]:
        reached[y, x + 1] = True; q.append((y, x + 1))

# `solid` also throws out the tile's anti-aliased rim: those pixels are neither transparent nor
# gradient-coloured, so the flood never claims them and they would otherwise survive as a thin
# rounded-rect ring around the whole splash. The bear sits far from the corners, so erosion never
# touches it.
bear = ~reached & solid
frac = bear.mean()
print('  bear mask: %.1f%% of source' % (100 * frac))
if not 0.05 < frac < 0.65:
    sys.exit('Bear mask looks wrong (%.1f%% of image) — segmentation failed, not writing' % (100 * frac))

# Feathered alpha, then crop to the bear with a small margin so the blur is not clipped.
mask_img = Image.fromarray((bear * 255).astype(np.uint8)).filter(ImageFilter.GaussianBlur(1.2))
ys, xs = np.nonzero(bear)
pad = 6
x0, x1 = max(0, xs.min() - pad), min(size, xs.max() + 1 + pad)
y0, y1 = max(0, ys.min() - pad), min(size, ys.max() + 1 + pad)
bear_rgba = Image.merge('RGBA', (*img.convert('RGB').split(), mask_img)).crop((x0, y0, x1, y1))
print('  bear bbox: %dx%d' % (bear_rgba.width, bear_rgba.height))

target = int(CANVAS * BEAR_FRAC)
scale = target / max(bear_rgba.size)
bear_big = bear_rgba.resize((round(bear_rgba.width * scale), round(bear_rgba.height * scale)), Image.LANCZOS)

canvas = Image.new('RGB', (CANVAS, CANVAS), CREAM)
px = (CANVAS - bear_big.width) // 2
py = int(CANVAS * CENTRE_Y) - bear_big.height // 2
canvas.paste(bear_big, (px, py), bear_big)

os.makedirs(OUT_DIR, exist_ok=True)
for name in OUT_NAMES:
    canvas.save(os.path.join(OUT_DIR, name), 'PNG')
print('✓ Wrote %s/{%s}  (%dx%d, bear %dx%d at (%d,%d), source=%s)' % (
    OUT_DIR, ','.join(OUT_NAMES), CANVAS, CANVAS, bear_big.width, bear_big.height, px, py,
    os.path.basename(src_path)))
print('  mode=%s  (flat RGB, no alpha)' % canvas.mode)
