#!/usr/bin/env python3
"""Build the 1024x1024 App Store icon from the Cubby bear.

WHY THIS EXISTS
`npx cap add ios` ships a placeholder AppIcon (Capacitor's blue X). TestFlight build 1+2 carried it.
Apple requires a 1024x1024 marketing icon that is SQUARE and OPAQUE: no alpha channel, no pre-rounded
corners (iOS applies its own squircle mask; a pre-rounded icon gets double-rounded and shows dark
slivers, and an alpha channel is an outright rejection).

Our source, icons/logo-512.png, is 512x512 WITH alpha and WITH rounded corners, and there is no vector
original. So we:
  1. Fit the cream background gradient from the artwork's own opaque border pixels (a plane fit per
     channel, which is exact for a linear gradient), and render it full-bleed to the corners. This
     continues the real artwork rather than inventing a flat colour that would band against it.
  2. Upscale the bear 2x with Lanczos and composite it over that background.
  3. Flatten to RGB so there is no alpha at all.

This is an upscale of 512 art, which is honest but not ideal. If a true 1024 (or vector) bear ever
exists, drop it in as icons/logo-1024.png and this script prefers it automatically.

`ios/` is gitignored and regenerated by `npx cap add ios`, so the generated icon is NOT durable —
re-run this after any regen. See docs/plans/2026-07-15-native-wrapper-app-store.md

Usage: python3 tools/gen_app_icon.py
"""
import os
import sys

import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PREFERRED = os.path.join(ROOT, 'icons', 'logo-1024.png')   # if a real 1024 ever lands, it wins
FALLBACK = os.path.join(ROOT, 'icons', 'logo-512.png')
OUT = os.path.join(ROOT, 'ios', 'App', 'App', 'Assets.xcassets', 'AppIcon.appiconset', 'AppIcon-512@2x.png')
SIZE = 1024

src_path = PREFERRED if os.path.exists(PREFERRED) else FALLBACK
if not os.path.exists(src_path):
    sys.exit('No source icon at %s' % src_path)

img = Image.open(src_path).convert('RGBA')
if img.size != (SIZE, SIZE):
    img = img.resize((SIZE, SIZE), Image.LANCZOS)

a = np.asarray(img).astype(np.float64)
alpha = a[:, :, 3]

# Erode the opaque region before trusting any of it. The rounded-rect boundary is a fringe of
# anti-aliased pixels whose alpha rounds to ~255 but whose COLOUR is blended toward white. Left in,
# they both skew the gradient fit and survive as "artwork", painting a bright arc exactly where the
# old corner was. MinFilter shrinks the opaque region away from every transparent neighbour.
solid = np.asarray(
    Image.fromarray(alpha.astype(np.uint8)).filter(ImageFilter.MinFilter(9))
) == 255

# Sample pure-background pixels: solidly opaque, and in the outer border band so the bear (centre)
# is excluded. The rounded corners are transparent, so they self-exclude.
band = int(SIZE * 0.06)
yy, xx = np.mgrid[0:SIZE, 0:SIZE]
border = (xx < band) | (xx >= SIZE - band) | (yy < band) | (yy >= SIZE - band)
mask = solid & border
if mask.sum() < 500:
    sys.exit('Not enough opaque border pixels to fit the background gradient (got %d)' % mask.sum())

# Quadratic surface fit per channel: c = k0*x + k1*y + k2*x^2 + k3*y^2 + k4*xy + k5.
# A plane is only exact for a strictly linear gradient; this one curves (a plane fit left residuals up
# to 27/255, which showed as a visible arc where the extended corners met the real artwork).
def design(x, y):
    x = x / SIZE
    y = y / SIZE
    return np.column_stack([x, y, x * x, y * y, x * y, np.ones(len(x))])

A = design(xx[mask].astype(np.float64), yy[mask].astype(np.float64))
full = design(xx.ravel().astype(np.float64), yy.ravel().astype(np.float64))
bg = np.zeros((SIZE, SIZE, 3), dtype=np.float64)
for ch in range(3):
    coef, *_ = np.linalg.lstsq(A, a[:, :, ch][mask], rcond=None)
    bg[:, :, ch] = (full @ coef).reshape(SIZE, SIZE)
    resid = np.abs(a[:, :, ch][mask] - (A @ coef))
    print('  channel %d: max residual %.1f/255, mean %.2f' % (ch, resid.max(), resid.mean()))
bg = np.clip(bg, 0, 255)

# Keep only the eroded-solid artwork; everything else becomes the reconstructed background. The bear
# sits well inside the rect on fully-opaque background, so erosion only ever eats the boundary fringe
# (which is background-coloured anyway and is regenerated exactly by the fit).
out = np.where(solid[:, :, None], a[:, :, :3], bg)
res = Image.fromarray(np.clip(out, 0, 255).astype(np.uint8), 'RGB')

os.makedirs(os.path.dirname(OUT), exist_ok=True)
res.save(OUT, 'PNG')
print('✓ Wrote %s  (%dx%d, source=%s)' % (OUT, SIZE, SIZE, os.path.basename(src_path)))
print('  mode=%s  alpha=%s  (Apple requires RGB / no alpha)' % (res.mode, 'no' if res.mode == 'RGB' else 'YES - REJECT'))
